sudo: required
services:
  - docker
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt

script: 
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # run docker build & tests
  - py.test -vv test/
