sudo: required
services:
  - docker
language: python
python:
  - "2.7"
install:
  - pip install tox

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # requirements, build docker, and tests
  - tox
