sudo: required
services:
  - docker
language: python
env:
    global:
        - QEMU_VER=v2.9.1
    matrix:
        - OS=debian ARCH=amd64
        - OS=debian ARCH=armhf
        - OS=debian ARCH=aarch64
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # generate and build dockerfile
  - ./Dockerfile.py --os=${OS} --arch=${ARCH} -v --no-build
  - docker build  --pull --cache-from="diginc/pi-hole:debian_${ARCH},pi-hole:debian_${ARCH}" -f Dockerfile_debian_${ARCH} -t pi-hole:debian_${ARCH} . 
  - docker images
  # run docker build & tests
  - py.test -vv -n auto -k "${OS}-${ARCH}" ./test/
