version: "3"
services:
  pihole:
    image: diginc/pi-hole:alpine
    environment:
      # enter your docker host IP here
      ServerIP:
      # IPv6 Address if your network supports it
      #ServerIPv6: 192.168.1.55
    volumes:
      - "./pihole/:/etc/pihole/"
      - "./dnsmasq.d/:/etc/dnsmasq.d/"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    restart: always
